server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: ERROR
    com.auth0.example: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: "<client_id>"
            client-secret: "<client_secret>"
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: "<issuer_uri>"
